[runner]
fastReruns = true

[server]
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false

[server.headers]
"Content-Security-Policy" = "frame-ancestors 'self' http://localhost:3000"

[theme]
base = "light"
font = "sans serif"
