[runner]
fastReruns = true
magicEnabled = false

[server]
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false
baseUrlPath = "/reimbursement-gen"
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
font = "sans serif"
